config/routes.rb
Preview::Application.routes.draw do

  resources :s3_uploads

  resources :events do
    collection do
      get 'list'
      get 'invite'
    end
  end

  resources :cron

  resources :metrics

  resources :welcome_wizard

  resource :whiteboard

  match 'signup', :to => 'users#signup'

  scope '/static' do
    match ':action' => 'static#:action'
    match 'resources/:page' => 'static#_resources'
  end

  match 'events/:id/invite' => 'events#invite'
  match 'events/:id/invite_email' => 'events#invite_email'
  match 'events/:id/rsvp' => 'events#rsvp'
  
  match 'signup', :to => 'users#create', :as => 'signup'
  match 'login', :to => 'users#login', :as => 'login'
  match 'jlogin' => 'users#login_json'
  match 'jregister' => 'users#create_json'
  match 'logout', :to => 'users#logout', :as => 'logout'
  match 'verify', :to => 'users#verify', :as => 'verify'
  match 'forgot_password', :to => 'users#forgot_password', :as => 'forgot_password'
  match 'change_password', :to => 'users#change_password', :as => 'change_password'  
  match 'update_settings' => 'users#update_settings'
  match 'email_settings' => 'users#email_settings'
  match 'change_org_info' => 'users#change_org_info'
  match 'change_picture', :to => 'users#change_picture'
  match 'create_profile', :to => 'teachers#create_profile'
  match 'callback', :to => 'teachers#callback'
  match 'linkedinprofile', :to => 'teachers#linkedinprofile'
  match 'change_school_picture/:id', :to => 'schools#change_school_picture'
  match 'skills', :to => 'skills#get'
  match 'crop', :to => 'users#crop'
  match 'crop_image', :to => 'users#crop_image'
  match 'crop_image_temp', :to => 'users#crop_image_temp'
  match 'crop_temp', :to => 'users#crop_temp'
  
  root :to => "home#index"
  match 'beta_teacher' => "alphas#teacher"
  match 'beta_admin' => "alphas#admin"
  match 'beta_general' => "alphas#general"
  
  match 'account/:id' => 'users#edit'
  match 'add_pin' => 'teachers#add_pin'
  match 'remove_pin' => 'teachers#remove_pin'
  match 'add_star' => 'teachers#add_star'
  match 'remove_star' => 'teachers#remove_star'
  match 'add_connection' => 'connections#add_connection'
  match 'remove_connection' => 'connections#remove_connection'
  match 'accept_connection' => 'connections#accept_connection'
  match 'remove_pending' => 'connections#remove_pending'
  match 'purge/:id' => 'teachers#purge'
  match 'users' => 'users#update'
  match 'attach' => 'teachers#attach'
  match 'teachers/:id/skills' => 'teachers#skills'
  match 'jobattach' => 'jobs#attach'
  match 'videos/record' => 'videos#record'
  match 'videos/create_snippet' => 'videos#create_snippet'
  match 'teacher_applications' =>'teachers#teacher_applications'
  match 'appattachments/:id' =>  'teachers#appattachments'
  match 'my_connections' => 'connections#my_connections'
  match 'pending_connections' => 'connections#pending_connections'
  match 'userconnections/:id' => 'connections#userconnections'
  match 'myvideo' => 'videos#myvideo'
  match 'inviteconnections' => 'connections#inviteconnections' 
  match 'inviteconnection' => 'connections#inviteconnection'
  match 'education', :to => 'teachers#education'
  match 'update_education' => 'teachers#update_education'
  match 'remove_education/:id' => 'teachers#remove_education'
  match 'edit_education/:id' => 'teachers#edit_education'
  match 'update_existing_education/:id' => 'teachers#update_existing_education'
  match 'teacherskills/:id' => 'skills#teacherskills'
  match 'add_embed' => 'videos#add_embed'
  
  match 'experience', :to => 'teachers#experience'
  match 'update_experience' => 'teachers#update_experience'
  match 'remove_experience/:id' => 'teachers#remove_experience'
  match 'edit_experience/:id' => 'teachers#edit_experience'
  match 'update_existing_experience/:id' => 'teachers#update_existing_experience'
  
  get "home/index"
  match 'share_on_whiteboard' => 'home#whiteboard_share'
  match 'delete_from_whiteboard' => 'home#whiteboard_rmv'
  match 'hide_from_whiteboard' => 'whiteboards#hide'
  match 'apply/:id' => 'jobs#apply'
  match 'kipp_apply/:id' => 'jobs#kipp_apply'
  match 'tfa_apply/:id' => 'jobs#tfa_apply'
  match 'apply_confirmation/:id' => 'jobs#apply_confirmation'
  match 'apply_confirmation' => 'jobs#apply_confirmation'
  match 'job_referral/:id' => 'jobs#job_referral'
  match 'job_referral' => 'jobs#job_referral'
  match 'job_referral_email/:id' => 'jobs#job_referral_email'
  match 'site_referral/:id' => 'home#site_referral'
  match 'site_referral' => 'home#site_referral'
  match 'site_referral_email' => 'home#site_referral_email'
  match 'school_signup' => 'home#school_signup'
  match 'create_admin' => 'users#create_admin'
  match 'my_jobs' => 'jobs#my_jobs'
  match 'forschools' => 'home#school_splash'
  match 'my_jobs/:school_id' => 'jobs#my_jobs'
  match 'my_schools' => 'schools#my_schools'
  match 'add_school' => 'schools#add_school'
  match 'applications/:id' => 'applications#index'
  match 'applications/reject/:id' => 'applications#reject'
  match 'applications/attachments/:id' => 'applications#attachments'
  match 'about' => 'home#about'
  match 'blog' => 'blog_entries#index'
  match 'privacy' => 'home#privacy'
  match 'termsofservice' => 'home#terms_of_service'
  match 'howitworks' => 'home#how_it_works_teachers'
  match 'howitworks/schools' => 'home#how_it_works_schools'
  match 'contact' => 'home#contact'
  match 'my_interviews' => 'interviews#my_interviews'
  match 'teachersignup' => 'alphas#beta'
  match 'resources' => 'home#resources'
  match 'customers' => 'home#customers'
  match 'press' => 'home#press'
  match 'school_thankyou' => 'home#school_thankyou'
  match 'dmca' => 'home#dmca'
  
  match 'admin' => 'users#teacher_user_list'
  match 'teachlist' => 'users#teacher_user_list'
  match 'schoollist' => 'users#school_user_list'
  match 'deactivatedlist' => 'users#deactivated_user_list'
  match 'pendingevents' => 'events#admin_events'
  match 'organizationlist' => 'users#organization_user_list'
  match 'blogadmin' => 'blog_entries#list'
  match 'fetch_code' => 'users#fetch_code'
  match 'jobattachpurge/:id' => 'jobs#jobattachpurge'
  
  match 'interviews/new' => 'interviews#new'
  match 'interviews/respond' => 'interviews#respond'
  resources :interviews
  match 'interviews/:id' => 'interviews#show'
  match 'messages/sent' => 'messages#sent'
  match 'new_member' => 'users#new_member'
  match 'edit_member/:id' => 'users#edit_member'
  match 'accounts/:id' => 'users#accounts'
  match 'manage/:id' => 'users#manage'
  match 'favorites' => 'teachers#favorites'
  match 'jobs/:id/jobattachments' => 'jobs#jobattachpost'
  match '/postattach' => 'jobs#jobattachpost'
  
  match 'teachers_faq' => 'home#teachers_faq'
  match 'schools_faq' => 'home#schools_faq'
  match 'update_details' => 'video#update_details'

  match 'card'      => 'card#get'
  match 'card/:url' => 'card#get'
  match 'cardeducation' => 'card#addEducation'
  match 'cardexperience' => 'card#addExperience'
  match 'cardcredential' => 'card#addCredential'
  match 'cardskills' => 'card#addSkills'
  match 'cardremoveskills' => 'card#removeSkills'
  match 'cardheadline' => 'card#cardheadline'
  match 'cardavatar' => 'card#cardavatar'
  match 'change_location' => 'card#change_location'

  match 'vouchrequest' => 'vouches#vouchrequest'
  match 'vouchresponse' => 'vouches#vouchresponse'
  match 'updatevouch' => 'vouches#updatevouch'
  match 'unlocked' => 'vouches#unlocked'

  
  resources :alphas
  resources :winks
  resources :reviews
  resources :jobs
  resources :applications
  resources :review_permissions
  resources :schools
  resources :teachers
  resources :videos
  resources :users
  resources :blogentries
  resources :organizations

  resources :pins
  resources :subjects
  resources :credentials
  resources :blog_entries
  resources :messages
  resources :connections do
    collection do
      get 'add_and_redir'
    end
  end
  
  match '/techstars' => 'home#video1'
  match '/techstarsteam' => 'home#video2'
  match '/upstartla' => 'home#video3'
  match '/harvardbiz' => 'home#video4'
  match '/demolesson' => 'home#how_it_works_teachers'
  match '/muckerlab' => 'home#muckerlab'

  match 'u/:guest_pass' => 'teachers#guest_entry'
  match '/:url/:guest_pass', :to => 'teachers#profile'
  match '/:url', :to => 'teachers#profile'

  match 'teachers/:id/view_history', :to => 'teachers#view_history'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'standard'
  
  USER_ID, PASSWORD = "upstartla", "incubator"
  USER_ID_M, PASSWORD_M = "muckerlab", "incubator"
  before_filter :authenticate, :only => [ :video1, :video2, :video3, :video4 ]
  before_filter :muckerlab_auth, :only => [ :muckerlab ]
    
  def index
    if not self.current_user.nil?
      if self.current_user.is_admin?
        @schools = self.current_user.all_schools
        
        @jobs = self.current_user.all_jobs_for_schools

        @activities = self.current_user.activities

        @pins = self.current_user.pins.count

        @administrators = self.current_user.organization.admincount

        @interviews = @jobs.inject(0) do |total, job|
          total += job.interviews.count
        end
        
        if self.current_user.is_shared && !self.current_user.is_limited
          #if shared and not limited user get the activities for the master admin
          admin = SharedUsers.find(:first, :conditions => { :user_id => self.current_user.id})
          @activities = @activities + Activity.find(:all, :conditions => ['user_id = ? OR user_id = 0', admin.owned_by], :order => 'created_at DESC')
        end

        @applicants = @jobs.inject(0) do |total, job|
          total += job.new_applicants.count
        end         
      elsif not self.current_user.teacher.nil?
        @whiteboard = Array.new
        Whiteboard.getActivity.paginate(:per_page => 5, :page => params[:page]).each do |post|
          @post = post
          @whiteboard << render_to_string('whiteboards/show', :layout => false)
        end

        @pendingcount = self.current_user.pending_connections.count

        @user = User.find(self.current_user)

        @jobs = Job.find(:all, :conditions => ['active = ?', true], :limit => 4, :order => 'created_at DESC')
        
        @featuredjobs = Job.find(:all, :conditions => ['active = ?', true], :order => 'created_at DESC')

        @interviews = self.current_user.teacher.interviews

        #Activites currently only deal with connections
        #Trying to only have a single query due to recent problems so using find_by_sql
        #Should change as soon as possible as this is database engine specific (currently MySQL)
        @activities = Activity.find_by_sql(['SELECT a.* FROM activities a, connections c WHERE c.owned_by = ? and a.creator_id = c.user_id and a.activityType = 10', self.current_user.id], :order => 'created_at DESC',:limit => 4)
      end
    end

    respond_to do |format|
      format.html # beta.html.erb
    end
  end
  
  def about
  end
  
  def privacy
  end
  
  def terms_of_service
  end
  
  def contact
  end
  
  def how_it_works_teachers
  end
  
  def how_it_works_schools
  end
  
  def video1
  end
  
  def video2
  end
  
  def video3
  end
  
  def video4
  end
  
  def muckerlab
  end
  
  def teachers_faq
   end

  def schools_faq
  end
  
  def site_referral
    unless self.current_user.nil?
      name = self.current_user.name
    else
      name = "[name]"
    end

    @default_message = "I'd love to add you to my professional teaching network at DemoLesson. We can
connect and the profile is super easy to make. Check it out!\n\n-#{name}"
  end

  def school_splash
  end
  
  def school_signup
  end
  
  def customers
  end  
  
  def press
  end  

  def school_thankyou
  end
  
  def dmca
  end
  
  def school_signup_email
     @signup = params[:signup]
     @name = @signup[:name]
     @schoolname = @signup[:schoolname]
     @email = @signup[:email]
     @phonenumber = @signup[:phonenumber]

     UserMailer.school_signup_email(@name, @schoolname, @email, @phonenumber).deliver

      respond_to do |format|
         format.html { redirect_to :school_thankyou}

      end
  end
  
  def site_referral_email

    if params[:referral][:teachername].nil? || params[:referral][:teachername].empty?
      flash[:notice] = "Name is required"
      return redirect_to '/site_referral'
    end

    if params[:referral][:emails].nil? || params[:referral][:emails].empty?
      flash[:notice] = "Email is required"
      return redirect_to '/site_referral'
    end

    # Get the post data key
    @referral = params[:referral]

    # Interpret the post data from the form
    @teachername = @referral[:teachername]
    @emails = @referral[:emails]
    @message = @referral[:message]

    # Swap out any instances of [name] with the name of the sender
    @message = @message.gsub("[name]", @teachername);

    # Swap out all new lines with line breaks
    @message = @message.gsub("\n", '<br />');

    # Get the current user if applicable
    user = self.current_user unless self.current_user.nil?

    # Send out the email to the list of emails
    UserMailer.refer_site_email(@teachername, @emails, @message, user).deliver

    # Return user back to the home page 
    respond_to do |format|
      format.html { redirect_to "http://www.demolesson.com", :notice => 'Email Sent Successfully' }
    end
  end

  def whiteboard_share
    redirect_to :root if self.current_user.nil?
    Whiteboard.createActivity(:share, "{user.teacher.profile_link} Shared: " + params[:message], '', {"deleteable" => true}) unless params[:message].nil?
    redirect_to :root
  end

  def whiteboard_rmv
    w = Whiteboard.find(params[:post])
    redirect_to :root if self.current_user.nil? || (w.user != self.current_user && !self.current_user.is_admin)
    w.destroy; redirect_to :root
  end
  
  private
   def authenticate
        authenticate_or_request_with_http_basic do |id, password| 
        id == USER_ID && password == PASSWORD
      end
   end
  
   def muckerlab_auth
        authenticate_or_request_with_http_basic do |id, password| 
        id == USER_ID_M && password == PASSWORD_M
   end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_dashboard.erb
== admin dashboard ==

app/views/home/_admin_dashboard.html.erb
<div id="userMenu" class="job_browser">

  <h1>Welcome, <%= self.current_user.first_name %>!</h1>

  <div id = "jobs">
     <img src="/assets/file.png" id = "file" class = "icon" height = "34" alt="file.png"/>
     <h_admin_dashboard>My Jobs</h_admin_dashboard></br>

     <% if @applicants == 0 %>
     <%= link_to 'No New Applicants', my_jobs_path %>
     <% elsif @applicants == 1 %>
     <%= link_to '1 New Applicant', my_jobs_path %>
     <% else %>
     <%= link_to @applicants.to_s+' New Applicants', my_jobs_path %>
     <% end %>

     <br />
     <%= @interviews %> Interviews<br />
     <% if @jobs.count == 0 %>
     No Active Job Posts
     <% else %>
     <%= link_to @jobs.count.to_s+" Active Job Posts", my_jobs_path %>
     <%= link_to "+", {:controller => :jobs, :action => :new}%>
     <% end %>
  </div>

  <div id = "favorites">
     <img src="/assets/favorite_star.png" id = "flag" class = "icon" height = "34" alt="placeholder.png"/>
     <h_admin_dashboard>Favorites</h_admin_dashboard><br />
     <% if @pins == 1 %>
       <%= link_to "1 total favorite", "/favorites" %>
     <% else %>
       <%= link_to @pins.to_s + " total favorites", "/favorites" %>
     <% end %>
  </div>


  <div id = "post">
	  <%= link_to "Post New Job", {:controller => :jobs, :action => :new}, {:class => "btn btn-success"} %>
  </div>

  <div id = "inbox">
     <img src="/assets/sfs_icon_forward.png" id = "inboxPic" class = "icon" height = "34" alt="sfs_icon_forward.png"/>
     <h_admin_dashboard>Inbox</h_admin_dashboard></br>

     <% if unread_messages == 0 %>
     <%= link_to "No New Messages", :messages %>
     <% else %>
     <%= link_to unread_messages.to_s+" Unread Messages", :messages %>
    <% end %>
  </div>

  <div id = "myOrg">
    <img src="/assets/admin_organization.png" id = "pic" class = "icon" height = "34" alt="placeholder.png"/>
    <h_admin_dashboard>My Organization</h_admin_dashboard></br>
    <%= pluralize(self.current_user.all_schools.count, "School") %> 
    <% if !self.current_user.is_limited %>
    <a href="/schools/new" id = "schools">+</a><br />
    <%= pluralize(@administrators, "Administrator") %> 
      <a href="/accounts/<%= self.current_user.id %>" id = "administrators">+</a><br />
    <% end %>
  </div>
  
</div>

<div id="page">
<h4>News Feed</h4>

<% if @activities.count == 0 %>
<div style="text-align:center; color: #999">No Current News Stories</div>
<% else %>
	<% @activities.each do |activity| %>
		<% if activity.activityType == 4 %>
			<p class="activity"><span>DemoLesson Blog</span><strong>New blog post:</strong> <%= link_to activity.blog_title, activity.blog_url %></p>
		<% elsif activity.activityType == 3 %>
                  <% if activity.application_job.active && activity.application.status == 1 %>
                    <p class="activity"><% if activity.creator.avatar? %><span class="img"><%= image_tag activity.creator.avatar.url(:tiny) %></span><% end %><span><%= activity.created_at.to_s(:due_time) %></span><strong><% if activity.teacher != nil %><%= link_to activity.creator.name, activity.teacher.url+'?application='+activity.application.id.to_s() %><% end %></strong> applied to your open position <%= link_to activity.application_job.title, activity.application_job %> at <%= link_to activity.application_school.name, activity.application_school %>.</p> 
                  <% end %>
		<% elsif activity.activityType == 2 %>
                  <% if activity.interview.date != Time.at(0) && activity.application_job.title != 'Not found' && activity.application_job.active && activity.application.status == 1 %>
                  <p class="activity"><% if activity.creator.avatar? %><span class="img"><%= image_tag activity.creator.avatar.url(:tiny) %></span><% end %><span><%= activity.created_at.to_s(:due_time) %></span><strong><%= link_to activity.creator.name, activity.teacher.url+'?application='+activity.application.id.to_s() %></strong> scheduled an interview at <% if activity.interview.date == Time.at(0) %><strong>not applicable</strong>
                <% else %>
                  <% if activity.interview.selected == 1 %>
                    <%= link_to activity.interview.date.to_s(:interview_time), '/applications/'+activity.application_job.id.to_s %>
                  <% elsif activity.interview.selected == 2 %>
                    <%= link_to activity.interview.date_alternate.to_s(:interview_time), '/applications/'+activity.application_job.id.to_s %>
                  <% else %>
                    <%= link_to activity.interview.date_alternate_second.to_s(:interview_time), '/applications/'+activity.application_job.id.to_s %>
                  <% end %>
                <% end %> for your position <%= link_to activity.application_job.title, activity.application_job %>.</p> 
              <%end %>
		<% elsif activity.activityType == 1 %>
			<p class="activity"><% if activity.creator.avatar? %><span class="img"><%= image_tag activity.creator.avatar.url(:tiny) %></span><% end %><span><%= activity.created_at.to_s(:due_time) %></span><strong><% if activity.teacher != nil %><%= link_to activity.creator.name, activity.teacher.url %><% end %></strong> sent you a message: <%= link_to activity.message.subject, activity.message %>.</p> 
		<% end %>
	<% end %>
<% end %>
</div>

app/views/home/_splash.html.erb
<section id="main-content">
	<div class="features-slider">
		<div id="featured">
			<img src="/assets/tioki/features-slide/feature-one.jpg" data-caption="#one-caption" />
			<img src="/assets/tioki/features-slide/feature-two.jpg" data-caption="#two-caption" />
			<img src="/assets/tioki/features-slide/feature-three.jpg" data-caption="#three-caption" />
			<img src="/assets/tioki/features-slide/feature-four.jpg" data-caption="#four-caption" />
		</div>
		<!-- Captions for Orbit -->
		<span class="orbit-caption" id="one-caption">
			<div class="signup-form">
				<h2>
				Educators Join Free
				</h2>
				<!--form action="/" id="signup-form">
					<fieldset>
						<input type="email" placeholder="Email" />
					</fieldset>
					<fieldset id="enterpwd">
						<input type="password" placeholder="Password" />
					</fieldset>
					<fieldset id="confirmpwd">
						<input type="password" placeholder="Confirm Password" />
					</fieldset>
					<fieldset>
						<input type="submit" class="button huge-button" value="Sign up for Tioki" />
					</fieldset>
					<p class="smalltext">
					By signing up, I agree to the <span><a href="#">terms</a></span>.
					</p>
				</form-->
				<p>Tioki will be launched soon! Be the first to know by clicking below.</p>
				<a href="/signup" style="background:#F66C4C;color:#FFF;margin:10px inherit;display:block;text-align:center;" class="button huge-button">Click here</a>
				<iframe src="http://www.facebook.com/plugins/facepile.php? 
	href=http://demolesson.com" scrolling="no" frameborder="0" style="border:none;  
	overflow:hidden; width:300px;" allowTransparency="true"></iframe> 
			</div>
			<div class="featured-quote">
				<blockquote>
				"Tioki made it so easy for me to showcase my talents and connect with other teachers."
				</blockquote>
			</div>
		</span>
		<span class="orbit-caption" id="two-caption">
			<div class="featured-box featured-box-right">
				<h1>
				Your professional digital portfolio
				</h1>
				<div class="box-divider">
				</div>
				<p>
				To find the job of your dreams
				</p>
				<!--a href="signup.html" class="goto-signup">
				Sign up now!
				</a-->
			</div>
		</span>
		<span class="orbit-caption" id="three-caption">
			<div class="featured-box featured-box-right">
				<h1>
				Connect with<br />
				other teachers
				</h1>
				<div class="box-divider">
				</div>
				<p>
				and build your network of<br />
				colleagues and schools
				</p>
				<!--a href="signup.html" class="goto-signup">
				Sign up now!
				</a-->
			</div>
		</span>
		<span class="orbit-caption" id="four-caption">
			<div class="featured-box featured-box-right">
				<h1>
				Share tips and lesson plans
				</h1>
				<div class="box-divider">
				</div>
				<p>
				and upload your demo lessons
				</p>
				<!--a href="signup.html" class="goto-signup button">
				Sign up now!
				</a-->
			</div>
		</span>
	</div>
	<section class="press inner-content">
		<h1>
		As featured on...
		</h1>
		<article class="featured-thumb">
			<img src="/assets/tioki/press/edsurge.png" alt="" />
		</article>
		<article class="featured-thumb">
			<img src="/assets/tioki/press/startupweekend.png" alt="" />
		</article>
		<article class="featured-thumb">
			<img src="/assets/tioki/press/TechCrunch.png" alt="" />
		</article>
		<article class="featured-thumb">
			<img src="/assets/tioki/press/teach.png" alt="" />
		</article>
		<article class="featured-thumb last-thumb">
			<img src="/assets/tioki/press/launchedu.png" alt="" />
		</article>
		<div class="clearfloat"></div>
	</section>
</section>

app/views/home/_teacher_dashboard.html.erb
<h6>
	<%= image_tag @user.avatar.url(:tiny) if @user.avatar? %>
	Welcome, <%= self.current_user.first_name %>!
	
	<div align="right" style=" margin-top:-25px">
			<%= link_to "Add Connections", inviteconnections_path, :class => 'btn btn-success'%>
	</div>
</h6>

<div id="sidebar" class="job_browser">

	<div id="myConnections">
		<img src="/assets/contacts.png" id = "myConnectionsPic" class = "icon" width = "34" alt="contacts.png"/>
		<h4>Connections</h4>
		<%= link_to "Add Connections", :inviteconnections %></br>
		<%= link_to 'My Connections', :my_connections %></br>
        <%= link_to "Pending Connections (" + pendingcount.to_s + ")", :pending_connections %><br />
	</div>

	<div id = "messages">
		<img src="/assets/envelope.png" id = "messagesPic" class = "icon" width = "35" alt="envelope.png"/>
		<h4>Inbox</h4>

		<% if unread_messages == 0 %>
			<%= link_to "No New Messages", :messages %>
		<% elsif unread_messages == 1 %>
			<%= link_to "1 Unread Message", :messages %>
		<% else %>
			<%= link_to unread_messages.to_s+" Unread Messages", :messages %>
		<% end %><br />
	</div>

</div>

<div id="content">

	<% unless @user.rsvp.empty? %>
		<div id="recentActivity">
			<h4 style="font-family: Arial, Helvetica, 'Nimbus Sans L', sans-serif;color:#000;text-shadow:#ccc 1px 1px 2px; float:left;margin-left:5px;width:100%;">Upcoming Events On Your Calendar</h4><br />

			<div style="clear:both;"></div>
			
			<% @user.rsvp.select{|x| x.published && (x.end_time.future? || x.end_time.today?)}.each do |event| %>
				<div style="display:block;border-bottom:2px #DADADA solid;margin-bottom:10px;">
					<h7><%= link_to(event.name + ' — ' + event.start_time.localtime.to_datetime.strftime("%m/%d/%Y at %l:%M%P") , event) %></h7>
					<p><%= event.description.split(' ')[0..25].join(' ') + "... " %> <%= link_to "Continued on event page.", event %></p>
				</div>
			<% end %>	
		</div>
	<% end %>

	<div id="recentActivity">
		<h4 style="font-family: Arial, Helvetica, 'Nimbus Sans L', sans-serif; color:#000; text-shadow:#ccc 1px 1px 2px; float:left; margin-left: -3px; width:100%;">My Bulletin Board</h4><br />

		<form action="/share_on_whiteboard" style="position:relative;left:-3px;">
			<table style="width:100%;">
				<td>
					<textarea name="message" class="css3-border-box" style="width:100%;height:50px;" placeholder="Share Something..."></textarea>
				</td>
				<td style="width:10px;">
					<input type="submit" class="btn btn-success css3-border-box" value="Share" />
				</td>
			</table>
		</form>
		
		<% @whiteboard.each do |post| %>
			<%= raw post %>
		<% end %>
		<a href="#whiteboard-more" class="btn" style="text-align:center;display:block;">Show More</a>
	</div>
</div>
<script type="text/javascript">
$(function() {
	$(".item_jobs").each(function(index, item) {
		if(index > 2) {
			$(item).css("display", "none");
		}
	});
	$("#more").click(function() {
		$(".item_jobs").css("display", "block");
			$("#more").text("Less");
			$("#more").addClass("less");
	});
	$(".less").click(function() {
		$(".item_jobs").each(function(index, item) {
			if(index > 2) {
				$(item).css("display", "none");
			}
		});
	});
});

// White board more
$(document).ready(function() {
	window.whiteboardPage = 1;
	window.whiteboardMax = false;
	$('a[href="#whiteboard-more"]').click(function(e) {
		e.preventDefault();

		// If we have already reached the end of the whiteboard then stop
		if(window.whiteboardMax) return false;
		
		// Get the number for the next page of data to pull
		window.whiteboardPage++;

		// Store for future use down the stack
		more = $(this);

		// Get the next pieces of activity via JSON
		$.getJSON('/whiteboard?page=' + window.whiteboardPage, function(data) {

			// If no data was returned handle by removing the button and erroring
			if(data.length == 0) {
				more.animate({"opacity": 0}, 700, function() {
					window.whiteboardMax = true;
					more.text('No More Updates');
					more.addClass('btn-danger');
					setTimeout(function() {
						more.animate({"opacity": 1}, 1000);
					}, 50);
				});
			}

			// For every element
			for(var x in data) {

				// Create the object, insert, and fade it in
				$(data[x]).css('display','none').insertBefore(more).fadeIn(700);
			}
		});

		return false;
	});
});
</script>

app/views/home/resources.html.erb
<div id="wrapper_global">
	<h1 class="green">Resources</h1>
	<p>Check back soon!</p>
</div>