config/routes.rb
Preview::Application.routes.draw do

  resources :s3_uploads

  resources :events do
    collection do
      get 'list'
      get 'invite'
    end
  end

  resources :cron

  resources :metrics

  resources :welcome_wizard

  resource :whiteboard

  match 'signup', :to => 'users#signup'

  scope '/static' do
    match ':action' => 'static#:action'
    match 'resources/:page' => 'static#_resources'
  end

  match 'events/:id/invite' => 'events#invite'
  match 'events/:id/invite_email' => 'events#invite_email'
  match 'events/:id/rsvp' => 'events#rsvp'
  
  match 'signup', :to => 'users#create', :as => 'signup'
  match 'login', :to => 'users#login', :as => 'login'
  match 'jlogin' => 'users#login_json'
  match 'jregister' => 'users#create_json'
  match 'logout', :to => 'users#logout', :as => 'logout'
  match 'verify', :to => 'users#verify', :as => 'verify'
  match 'forgot_password', :to => 'users#forgot_password', :as => 'forgot_password'
  match 'change_password', :to => 'users#change_password', :as => 'change_password'  
  match 'update_settings' => 'users#update_settings'
  match 'email_settings' => 'users#email_settings'
  match 'change_org_info' => 'users#change_org_info'
  match 'change_picture', :to => 'users#change_picture'
  match 'create_profile', :to => 'teachers#create_profile'
  match 'callback', :to => 'teachers#callback'
  match 'linkedinprofile', :to => 'teachers#linkedinprofile'
  match 'change_school_picture/:id', :to => 'schools#change_school_picture'
  match 'skills', :to => 'skills#get'
  match 'crop', :to => 'users#crop'
  match 'crop_image', :to => 'users#crop_image'
  match 'crop_image_temp', :to => 'users#crop_image_temp'
  match 'crop_temp', :to => 'users#crop_temp'
  
  root :to => "home#index"
  match 'beta_teacher' => "alphas#teacher"
  match 'beta_admin' => "alphas#admin"
  match 'beta_general' => "alphas#general"
  
  match 'account/:id' => 'users#edit'
  match 'add_pin' => 'teachers#add_pin'
  match 'remove_pin' => 'teachers#remove_pin'
  match 'add_star' => 'teachers#add_star'
  match 'remove_star' => 'teachers#remove_star'
  match 'add_connection' => 'connections#add_connection'
  match 'remove_connection' => 'connections#remove_connection'
  match 'accept_connection' => 'connections#accept_connection'
  match 'remove_pending' => 'connections#remove_pending'
  match 'purge/:id' => 'teachers#purge'
  match 'users' => 'users#update'
  match 'attach' => 'teachers#attach'
  match 'teachers/:id/skills' => 'teachers#skills'
  match 'jobattach' => 'jobs#attach'
  match 'videos/record' => 'videos#record'
  match 'videos/create_snippet' => 'videos#create_snippet'
  match 'teacher_applications' =>'teachers#teacher_applications'
  match 'appattachments/:id' =>  'teachers#appattachments'
  match 'my_connections' => 'connections#my_connections'
  match 'pending_connections' => 'connections#pending_connections'
  match 'userconnections/:id' => 'connections#userconnections'
  match 'myvideo' => 'videos#myvideo'
  match 'inviteconnections' => 'connections#inviteconnections' 
  match 'inviteconnection' => 'connections#inviteconnection'
  match 'education', :to => 'teachers#education'
  match 'update_education' => 'teachers#update_education'
  match 'remove_education/:id' => 'teachers#remove_education'
  match 'edit_education/:id' => 'teachers#edit_education'
  match 'update_existing_education/:id' => 'teachers#update_existing_education'
  match 'teacherskills/:id' => 'skills#teacherskills'
  match 'add_embed' => 'videos#add_embed'
  
  match 'experience', :to => 'teachers#experience'
  match 'update_experience' => 'teachers#update_experience'
  match 'remove_experience/:id' => 'teachers#remove_experience'
  match 'edit_experience/:id' => 'teachers#edit_experience'
  match 'update_existing_experience/:id' => 'teachers#update_existing_experience'
  
  get "home/index"
  match 'share_on_whiteboard' => 'home#whiteboard_share'
  match 'delete_from_whiteboard' => 'home#whiteboard_rmv'
  match 'hide_from_whiteboard' => 'whiteboards#hide'
  match 'apply/:id' => 'jobs#apply'
  match 'kipp_apply/:id' => 'jobs#kipp_apply'
  match 'tfa_apply/:id' => 'jobs#tfa_apply'
  match 'apply_confirmation/:id' => 'jobs#apply_confirmation'
  match 'apply_confirmation' => 'jobs#apply_confirmation'
  match 'job_referral/:id' => 'jobs#job_referral'
  match 'job_referral' => 'jobs#job_referral'
  match 'job_referral_email/:id' => 'jobs#job_referral_email'
  match 'site_referral/:id' => 'home#site_referral'
  match 'site_referral' => 'home#site_referral'
  match 'site_referral_email' => 'home#site_referral_email'
  match 'school_signup' => 'home#school_signup'
  match 'create_admin' => 'users#create_admin'
  match 'my_jobs' => 'jobs#my_jobs'
  match 'forschools' => 'home#school_splash'
  match 'my_jobs/:school_id' => 'jobs#my_jobs'
  match 'my_schools' => 'schools#my_schools'
  match 'add_school' => 'schools#add_school'
  match 'applications/:id' => 'applications#index'
  match 'applications/reject/:id' => 'applications#reject'
  match 'applications/attachments/:id' => 'applications#attachments'
  match 'about' => 'home#about'
  match 'blog' => 'blog_entries#index'
  match 'privacy' => 'home#privacy'
  match 'termsofservice' => 'home#terms_of_service'
  match 'howitworks' => 'home#how_it_works_teachers'
  match 'howitworks/schools' => 'home#how_it_works_schools'
  match 'contact' => 'home#contact'
  match 'my_interviews' => 'interviews#my_interviews'
  match 'teachersignup' => 'alphas#beta'
  match 'resources' => 'home#resources'
  match 'customers' => 'home#customers'
  match 'press' => 'home#press'
  match 'school_thankyou' => 'home#school_thankyou'
  match 'dmca' => 'home#dmca'
  
  match 'admin' => 'users#teacher_user_list'
  match 'teachlist' => 'users#teacher_user_list'
  match 'schoollist' => 'users#school_user_list'
  match 'deactivatedlist' => 'users#deactivated_user_list'
  match 'pendingevents' => 'events#admin_events'
  match 'organizationlist' => 'users#organization_user_list'
  match 'blogadmin' => 'blog_entries#list'
  match 'fetch_code' => 'users#fetch_code'
  match 'jobattachpurge/:id' => 'jobs#jobattachpurge'
  
  match 'interviews/new' => 'interviews#new'
  match 'interviews/respond' => 'interviews#respond'
  resources :interviews
  match 'interviews/:id' => 'interviews#show'
  match 'messages/sent' => 'messages#sent'
  match 'new_member' => 'users#new_member'
  match 'edit_member/:id' => 'users#edit_member'
  match 'accounts/:id' => 'users#accounts'
  match 'manage/:id' => 'users#manage'
  match 'favorites' => 'teachers#favorites'
  match 'jobs/:id/jobattachments' => 'jobs#jobattachpost'
  match '/postattach' => 'jobs#jobattachpost'
  
  match 'teachers_faq' => 'home#teachers_faq'
  match 'schools_faq' => 'home#schools_faq'
  match 'update_details' => 'video#update_details'

  match 'card'      => 'card#get'
  match 'card/:url' => 'card#get'
  match 'cardeducation' => 'card#addEducation'
  match 'cardexperience' => 'card#addExperience'
  match 'cardcredential' => 'card#addCredential'
  match 'cardskills' => 'card#addSkills'
  match 'cardremoveskills' => 'card#removeSkills'
  match 'cardheadline' => 'card#cardheadline'
  match 'cardavatar' => 'card#cardavatar'
  match 'change_location' => 'card#change_location'

  match 'vouchrequest' => 'vouches#vouchrequest'
  match 'vouchresponse' => 'vouches#vouchresponse'
  match 'updatevouch' => 'vouches#updatevouch'
  match 'unlocked' => 'vouches#unlocked'

  
  resources :alphas
  resources :winks
  resources :reviews
  resources :jobs
  resources :applications
  resources :review_permissions
  resources :schools
  resources :teachers
  resources :videos
  resources :users
  resources :blogentries
  resources :organizations

  resources :pins
  resources :subjects
  resources :credentials
  resources :blog_entries
  resources :messages
  resources :connections do
    collection do
      get 'add_and_redir'
    end
  end
  
  match '/techstars' => 'home#video1'
  match '/techstarsteam' => 'home#video2'
  match '/upstartla' => 'home#video3'
  match '/harvardbiz' => 'home#video4'
  match '/demolesson' => 'home#how_it_works_teachers'
  match '/muckerlab' => 'home#muckerlab'

  match 'u/:guest_pass' => 'teachers#guest_entry'
  match '/:url/:guest_pass', :to => 'teachers#profile'
  match '/:url', :to => 'teachers#profile'

  match 'teachers/:id/view_history', :to => 'teachers#view_history'
  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  acts_as_mappable
  
  belongs_to :user
  attr_protected :user_id

  has_and_belongs_to_many :credentials
  has_and_belongs_to_many :subjects

  has_many :videos
  has_many :applications
  has_many :stars
  has_many :pins
  has_many :interviews
  
  has_many :experiences, :order => 'startYear DESC'
  has_many :educations, :order => 'current DESC, year DESC, start_year DESC'
  
  has_many :assets, :dependent => :destroy
  has_many :skills, :through => :user
  
  validates_associated :assets
  validates_uniqueness_of :url, :message => "The name you selected is not available."
  #validates_format_of :url, :with => /\w/, :message => "Invalid URL.", :unless => Teacher.new { |t| t.url.blank? }

  def self.find_or_create_from_user(user_id)
    original_user = User.find(user_id)
    if (original_user.present?)
      teacher = Teacher.find(:first, :conditions => {:user_id => user_id}) || Teacher.create!(:user_id => user_id)
      if (teacher.nil?)
        teacher = Teacher.create!(:user_id => user_id)
        teacher[:user_id] = user_id
        teacher.save
      end
    else
      teacher = nil
    end
    return(teacher)
  end

  def self.search(search)
    if search
      #check if search if an email or a name
      if search.include? "@"
        find(:all, :include => :user, :conditions => ['teachers.user_id = users.id && users.email LIKE ?', "%#{search}%"])
      else
        find(:all, :include => :user, :conditions => ['teachers.user_id = users.id && users.name LIKE ?', "%#{search}%"])
      end
    else
      find(:all)
    end
  end
  
  def self.owner_id(owner_id)
    @teacher = Teacher.find(owner_id)
    return @teacher.user_id
  end

  def vjs_embed_code(output_url)
    return "<video id=\"my_video_1\" class=\"video-js vjs-default-skin\" controls
		  preload=\"auto\" width=\"545\" height=\"429\"
		  data-setup=\"{}\"><source src=\"#{output_url}\" type='video/mp4'>
		</video>"
  end
  
  def no_embed_code
    return "<div align=\"center\" style=\"padding-top:200px\"><strong>This teacher has not yet uploaded a video, or it is processing.</strong></div>"
  end

  def snippet_watchvideo_button
    @video = Video.find(:first, :conditions => ['teacher_id = ? AND is_snippet=?', self.id, true], :order => 'created_at DESC')
    if @video != nil
      embedstring= "<a rel=\"shadowbox;width=545;height=429;player=iframe\" href=\"/videos/#{@video.id.to_s}\" class='btn'>Watch Snippet</a>"

      begin
        if @video.encoded_state == 'queued'
          Zencoder.api_key = 'ebbcf62dc3d33b40a9ac99e623328583'
          @status = Zencoder::Job.progress(@video.job_id)
          if @status.body['outputs'][0]['state'] == 'finished'
            @video.encoded_state = 'finished'
            @video.save
            return embedstring
          else
            return ""
          end
        else 
          return embedstring
        end
      rescue
        return ""
      end
    else
      return ""
    end
  end

  def snippet_watchvideo_test
    @video = Video.find(:first, :conditions => ['teacher_id = ? AND is_snippet=?', self.id, true], :order => 'created_at DESC')
    if @video != nil
      embedstring = "<a rel=\"shadowbox;width=545;height=429;player=iframe\" href=\"/videos/#{@video.id.to_s}\" class='btn'>Watch Snippet</a>"
    begin
      if @video.encoded_state == 'queued'
        Zencoder.api_key = 'ebbcf62dc3d33b40a9ac99e623328583'
        @status = Zencoder::Job.progress(@video.job_id)
        if @status.body['outputs'][0]['state'] == 'finished'
          @video.encoded_state = 'finished'
          @video.save
          return embedstring
        else
          if @status.body['outputs'][0]['state'] == 'failed'
            return "The snippet was unable to encode. Please check your start time." 
          else
            return "Processing..."
          end
        end
      else 
        return embedstring
      end
    rescue
      return "The snippet is currently doesn't exist or is encoding."
    end
    else
      return "You currently do not have a snippet."
    end
  end

  def vjs_test_embed
    @video = Video.find(:first, :conditions => ['teacher_id = ? AND is_snippet=?', self.id, false], :order => 'created_at DESC')
    if @video != nil
      embedstring=   "<video id=\"my_video_1\" class=\"video-js vjs-default-skin\" controls
                  preload=\"auto\" width=\"545\" height=\"429\"
                  data-setup=\"{}\"><source src=\"#{@video.output_url}\" type='video/mp4'>
                </video>"
      begin
        if @video.encoded_state == 'queued'
          Zencoder.api_key = 'ebbcf62dc3d33b40a9ac99e623328583'
          @status = Zencoder::Job.progress(@video.job_id)
          if @status.body['outputs'][0]['state'] == 'finished'
            @video.encoded_state = 'finished'
            @video.save
            return embedstring
          else
            return "The video is currently encoding."
          end
        else 
          return embedstring
        end
      rescue
        return "Video is doesn't exist or is currently encoding."
      end
    else
      return "You currently do not have a video. Upload one now!"
    end
  end
  # Viddler API helpers
  
  def viddler_embed_code(video_info)
   return "<object width=\"545\" height=\"429\" id=\"viddlerOuter-386968dc\" type=\"application/x-shockwave-flash\" data=\"//www.viddler.com/mini/#{video_info}\"> <param name=\"movie\" value=\"//www.viddler.com/mini/#{video_info}\"> <param name=\"allowScriptAccess\" value=\"always\"><param name=\"allowNetworking\" value=\"all\"><param name=\"allowFullScreen\" value=\"true\"><param name=\"flashVars\" value=\"f=1&autoplay=f&disablebranding=1&loop=0&hd=0\"></object>"
  end
  
  def error_embed_code
    return "<div id=\"video_placeholder\">Video could not be loaded</div>"
  end
  
  def placeholder_embed_code
    return "<div id=\"video_placeholder\">This teacher doesn\'t have a video yet.</div>"
  end
  
  def create_guest_pass
      self.guest_code = rand(36**8).to_s(36)
  end
  
  ## Attached file methods
  
  def new_asset_attributes=(asset_attributes) 
    assets.build(asset_attributes)
    #asset_attributes.each do |attributes| 
    #  assets.build(attributes)
    #end 
  end
  
  def existing_asset_attributes=(asset_attributes) 
    assets.reject(&:new_record?).each do |asset| 
      attributes = asset_attributes[asset.id.to_s] 
      if attributes 
        asset.attributes = attributes 
      else 
        asset.delete(asset) 
      end 
    end
  end
  
  def save_assets 
    assets.each do |asset| 
      asset.save
    end
  end

  def profile_link
    return "<a href=\"/#{self.url}\">#{self.user.name}</a>"
  end
  
end

app/helpers/teachers_helper.rb
module TeachersHelper
  def add_asset_link(name) 
      link_to_function name do |page| 
        page.insert_html :bottom, :assets, :partial => 'asset', :object => Asset.new 
      end 
  end
end

app/views/teachers/_asset.html.erb
<div class="asset"> 
  <% new_or_existing = asset.new_record? ? 'new' : 'existing' %>
  <% prefix = "teacher[#{new_or_existing}_asset_attributes][]" %>
  
  <% fields_for prefix, asset do |asset_form| -%> 
    <p> 
      Asset: <%= asset_form.file_field :file %> 
      <%= link_to_function "remove", "$(this).up('.asset').remove()" %> 
    </p> 
<% end -%> 
</div>

app/views/teachers/_attachments.html.erb
<h3>My Guest Passcode</h3>

<% if @teacher.guest_code != nil %>
<%= text_field :a, :b, :value => "http://demolesson.com/u/"+@teacher.guest_code.to_s, :class => :guest_pass_field %>
<% end %>

<p>Send this to people who don’t have a DemoLesson account to allow them to view your profile.</p>

<div>
<%= link_to 'Import from Linkedin!', '/linkedinprofile', :class => "btn btn-primary" %>

<p>Already have a LinkedIn Profile? You can import your experience, education, contact info, and other information directly from LinkedIn, saving you precious time. It only takes a few seconds.<%= link_to 'Try it now!', '/linkedinprofile' %></p>
</div>

<h3>Attachments</h3>

<% for asset in @teacher.assets %>
  <% if asset.assetType != 1 %>
    <p>
    <img src="<%= asset_path 'file.png' %>" />
    <%= link_to asset.name, asset.file.url %> <span class="purge"><%= link_to 'Remove?', '/purge/'+asset.id.to_s, :confirm => 'Are you sure you want to remove "'+asset.name+'" from your profile? The file be permanently deleted.' %></span><br />
    <%= asset.description %>
    </p>
<% end %>
<% end %>

<div id="attach_form" style="display: none">
<%= form_for @asset, :as => :asset, :url => '/attach', :html => { :multipart => true } do |f| %>

<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :description %><br />
	<%= f.text_field :description %>
</div>

<div class="field">
  <%= f.label :file %><br />
  <%= f.file_field :file %>
</div>

<p style="font-size: 11px"><a href="#" class="tooltip">Suggested uploads [?] <span>Resume &middot; Letter of recommendation &middot; Certificates or credentials &middot; Unit plan &middot; Pacing plan &middot; Lesson plan
&middot; Assessment &middot; Assessment tracker &middot; Classroom management plan &middot; Classroom procedures and protocol</span></a>

<div>
    <input name="commit" type="submit" value="Upload File" onclick="$('#loader').show('fast');" class="btn btn-success" />
</div>

<div id="loader" style="display: none">
	<img src="<%= asset_path 'loader.gif' %>" />
</div>

<% end %>
</div>

app/views/teachers/_form.html.erb
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<link type="text/css" href="/assets/jquery-ui-1.8.20.custom/css/blitzer/jquery-ui-1.8.20.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="/assets/jquery-ui-1.8.20.custom/js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/assets/jquery-ui-1.8.20.custom/js/jquery-ui-1.8.20.custom.min.js"></script>


<p class="notice">View a <%= link_to 'sample profile', 'http://demolesson.com/Mandela' %> to see what your completed one will look like.</p>

<div>
	
<%= link_to 'Education', '/education', :class => "btn" %>
<%= link_to 'Experience', '/experience', :class => "btn" %>
<%= link_to 'Credentials', '/credentials', :class => "btn" %>
	
<div style="float:right">
<%= link_to 'Change Profile Picture', '/change_picture', :class => "btn" %>
<% if @video == nil && @teacher.video_embed_url == nil %>
  <%= link_to "Upload Video", '/videos/new', :class => "btn btn-success"%>
<% else %>
  <%= link_to "Edit Video", '/myvideo', :class => "btn"%>
<% end %>

</div>

</div>

<div id="right" class="attached">
	<%= render :partial => 'attachments' %>
	<div id="attach_new_btn">
	<input name="attach" type="button" value="Attach New File" onclick="$('#attach_form').show('fast'); $('#attach_new_btn').hide();" class="btn btn-success" />
	</div>
	
	
</div>



<div id="left_editing">
<%= form_for @teacher, :as => :teacher, :url => '/teachers/'+@teacher.id.to_s, :html => { :multipart => true } do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h3>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %><% if msg == "The name you selected is not available." %> <%= link_to "Go back and pick another name",  :create_profile %><% end %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Headline</h3>
  The headline is limited to 140 characters
  <p id = "headlineCounter">140 chars</p><br />
  <div id ="headlineTextField" class="field"><%= f.text_area :headline, :rows => 7 , :maxlength => 140 %></div>


  <script>
      $(function() {
          var counter = 140;
          $("#headlineTextField").bind('keydown', function(e) {
               if (counter < 140 && e.which === 8) {
                   counter = counter + 1;
               } else if (counter ===140 && e.which === 8) {
                   counter = 140;
               }
               $("#headlineCounter").text(counter + " chars");
           });

          $("#headlineTextField").bind('keyup', function(e) {
               if (e.which !== 8) {
                  counter = counter - 1;
                  if (counter < 0) {
                     counter = 0;
                  }
               }
                $("#headlineCounter").text(counter + " chars");
          });
      });
  </script>   

  <h3>Current Position</h3>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field :school %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <h3>Seeking</h3>

  <div class="field">
    <%= f.check_box :currently_seeking %> <%= f.label :currently_seeking %>
  </div>

  <div class="field">
    <%= f.label :seeking_subject %><br />
    <%= f.text_field :seeking_subject %>
  </div>

  <div class="field">
    <%= f.label :seeking_grade %><br />
    <%= f.text_field :seeking_grade %>
  </div>

  <div class="field">
    <%= f.label :seeking_location %><br />
    <%= f.text_field :seeking_location %>
  </div>

  <h3>Additional Information</h3>

  <div class="field"><%= f.text_area :additional_information, :rows => 7 %></div>
  
  <div class = "field">
     <label for = "skillList" id="skillLabel">Skills</label> 
     <%= select 'skill', 'skillList', Skill.all.collect { |skill| [skill.name, skill.id] } %>
     
     <button type = "button" id = "addSkill">Add Skill</button>
     <div style = "height: 150px; width: 300px;" id = "skills">
     </div>
     
     <script>
       $(document).ready(function () {
           "use strict";
           var skillId, skillValue, tab, counter = 0;

           //Populate with current skills
           <% @skills.each do |skill| %>
           skillValue = "<%= skill.name %>";
           skillId = <%= skill.id%>;
           tab = document.createElement('div');
           tab.count = counter;
           $(tab).addClass('skillTab');
           $(tab).append('<a href="/teacherskills/' + skillId + '" id = "tabLink">' + skillValue + '</a>');
           $(tab).append('<input type="hidden" name="skills[]" value="' + skillId + '" />'); 
           $("#skills").append(tab);
           $(tab).append('<img class = "closePic" src="/assets/x-icon.png" style="z-index: 1;margin-bottom:-3px;cursor:pointer;">');
           counter += 1;


           <% end %>
           $("#addSkill").click(function () {
               skillValue = $("#skill_skillList option:selected").text();
               skillId = $("#skill_skillList option:selected").val();
               tab = document.createElement('div');
               tab.count = counter;
               $(tab).addClass('skillTab');
               $(tab).append('<a href="/teacherskills/' + skillId + '" id = "tabLink">' + skillValue + '</a>');
               $(tab).append('<input type="hidden" name="skills[]" value="' + skillId + '" />'); 
               $("#skills").append(tab);
               $(tab).append('<img class = "closePic" src="/assets/x-icon.png" style="z-index: 1;margin-bottom:-3px;cursor:pointer;">');
               counter += 1;
           });
           $("img.closePic").live("click", function () {
               $(this).closest("div.skillTab").remove();
           });
       });
     </script>
  </div>   
  
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label "LinkedIn Profile" %><br />
	<% if @teacher.linkedin == nil %>
    <%= f.text_field :linkedin, :value => "http://linkedin.com/" %>
	<% else %>
	<%= f.text_field :linkedin %>
	<% end %>
  </div>

  <h3>Options</h3>

  <div class="field">
    <%= f.check_box :willing_to_move %> <%= f.label :willing_to_move %>
  </div>
  
<div>
    <%= f.submit "Save Changes", :class => "btn btn-success" %>
  </div>

<% end %>
</div>

<div id="tipbox" style="margin-top: 480px">
	<div id="videotip" style= "margin: 5px 0px 5px 5px">
		<img src="<%= asset_path 'dl_play_button.png' %>" style="height: 20px; width:auto;">
		<p style ="font-size:16px; color:#5A5B5D; margin: -30px 0px 0px 25px;"> Video Tips</p>
	</div>
	<p style="font: lighter 14px Helvetica; color:#505050; margin-left:5px; margin-top: -12px;">Think your video is ready? Go through our check list to make sure your video includes everything it needs to show your skills off! Click <%= link_to "here.", "#" %> </p>
</div>

app/views/teachers/appattachments.erb
<% for asset in @teacher.assets %>
  <% if asset.application_id == @application.id %>
    <p class="attached">
    <img src="<%= asset_path 'file.png' %>" />
    <%= link_to asset.name, asset.file.url %> <span class="purge"><%= link_to 'Remove?', '/purge/'+asset.id.to_s, :confirm => 'Are you sure you want to remove "'+asset.name+'" from your profile? The file will be permanently deleted.' %></span><br />
    <%= asset.description %>
    </p>
  <% end %>
<% end %>

<div id="attach_form" style="display: none">
	<%= form_for @asset, :as => :asset, :url => '/jobattach', :html => { :multipart => true } do |f| %>

<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :description %><br />
	<%= f.text_field :description %>
</div>

<div class="field">
  <%= f.label :file %><br />
  <%= f.file_field :file %>
</div>

<div class="field">
  <%= f.hidden_field :application_id, {:value => @application.id} %>
</div>

<div>
    <input name="commit" type="submit" value="Upload File" onclick="$('#loader').show('fast');" class="btn btn-success" />
</div>

<div id="loader" style="display: none">
	<img src="<%= asset_path 'loader.gif' %>" />
</div>

<% end %>

</div>
	<div id="attach_new_btn">
	<input name="attach" type="button" value="Attach New File" onclick="$('#attach_form').show('fast'); $('#attach_new_btn').hide();" class="btn btn-success" />
	</div>
	
	 <%= link_to 'Back', :teacher_applications, :class => "btn" %>
</div>

app/views/teachers/linkedinprofile.html.erb
<h3>Do you have a linkedin profile and wish to use information from it as part of your demolesson profile?</h3>

<div>
<%= form_tag :action=> "linkedinprofile" do %>
  		<%= hidden_field_tag :response, :yes %>
		<%= submit_tag "Import Now", :class => "btn btn-success" %>

		<%= link_to "No Thanks", '/'+self.current_user.teacher.url, :class => "btn" %>
	
<% end %>
</div>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>